# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CnBEAxYMs4j8RhyhnqbM11o-6nomvBf8
"""

!pip install streamlit --quiet

import streamlit as st
import pandas as pd

# Load CSV
df = pd.read_csv("Project_details.csv")

st.title("📊 Project Task Dashboard")

name = st.selectbox("👤 Select a person", sorted(df["Name"].unique()))
activities = df[df["Name"] == name]["Activity"].unique()
activity = st.selectbox("⚙️ Select an activity", activities)

task_row = df[(df["Name"] == name) & (df["Activity"] == activity)].iloc[0]

st.markdown("### ✅ Task Details")
st.write(f"**Project:** {task_row['Project']}")
st.write(f"**Activity:** {task_row['Activity']}")
st.write(f"**Status:** {task_row['Completion Status']}")
st.write(f"**Time Allotted:** {task_row['Time Allotment (Hours)']} hours")
st.write(f"**Allocated Date:** {task_row['Allocated date']}")
st.write(f"**Completed Date:** {task_row['Completed date']}")
st.write(f"**Month:** {task_row['Month']}")
st.write(f"**Job Reference:** {task_row['Job reference']}")